### ISSUE TITLE
miscellaneous.cpp: A code bug?

### ISSUE THREAD

**Issue by aqing1987** [darealshinji/qpdfview#1]
Hi,
I think the code below in file miscellaneous.cpp is a bug, there are two SIGNAL
`
connect(tabBar, SIGNAL(tabDragRequested(int)), SIGNAL(tabDragRequested(int)));
`

**Comment by darealshinji** [comment]
Can you make a bug report to the upstream developers? https://bugs.launchpad.net/qpdfview

**Comment by aqing1987** [comment]
ok, thanks.
