### ISSUE TITLE
Unable to open files in new tab on Windows

### ISSUE THREAD

**Issue by DStalkerBR** [darealshinji/qpdfview#3]
Hi,
I would like to know how to always open files in a new tab on **Windows**.  
Currently, when I open files through Windows Explorer, they always open in a new window.

I attempted to use the `--unique` argument, but it had no effect.

**Comment by darealshinji** [comment]
Hmm. It looks looks like I have to compile it with DBus support or find another simple solution that works in Windows.

**Comment by darealshinji** [comment]
It builds with DBus enabled but it still doesn't work. I will further investigate this but I probably have to make a bug report to the upstream devs. It works well on Linux however.

**Comment by DStalkerBR** [comment]
I managed to make this configuration work by running the `dbus-launch.exe` binary available at the [Qt Project mailing list](https://lists.qt-project.org/pipermail/development/2014-December/019502.html) and adding the `--unique` argument to the registry entry at `HKCU\Software\Classes\Applications\qpdfview\shell\open\command\`.

I'm only experiencing an issue with the window failing to auto-focus upon opening the second file, it works only when opening the first file. (A similar issue has been discussed in [this thread](https://answers.launchpad.net/qpdfview/+question/239147) ) But it may not be specific to the application itself.

<sub>Also for some reason no terminal command, including `qpdfview.exe --help`, is producing any text output for me in the Windows terminal</sub>

**Comment by darealshinji** [comment]
> I managed to make this configuration work by running the `dbus-launch.exe` binary available at the [Qt Project mailing list](https://lists.qt-project.org/pipermail/development/2014-December/019502.html) and adding the `--unique` argument to the registry entry at `HKCU\Software\Classes\Applications\qpdfview\shell\open\command\`.

Next time I will ship the DBus binaries too.

> Also for some reason no terminal command, including `qpdfview.exe --help`, is producing any text output for me in the Windows terminal

Maybe it's better to show the commands in a window when calling it with `qpdfview.exe --help`, like many other applications do on Windows.

![help](https://github.com/darealshinji/qpdfview/assets/5700937/6f9f788d-98d8-4abd-8749-60e33da367ba)

**Comment by DStalkerBR** [comment]
> Maybe it's better to show the commands in a window when calling it with `qpdfview.exe --help`, like many other applications do on Windows.

Indeed.
Currently, I only managed to get the command output is by redirecting it to a file `qpdfview.exe --help > file.txt`.

**Comment by darealshinji** [comment]
The changes were added to upstream: https://bazaar.launchpad.net/~adamreichold/qpdfview/trunk/revision/2154
