### ISSUE TITLE
How build it for Windows

### ISSUE THREAD

**Issue by abdulbadii** [darealshinji/qpdfview#4]
How do we build one for Windows by use of Msys2/Mingw64
Please elaborate all requirements and steps to accomplish that

**Comment by darealshinji** [comment]
It shouldn't be too different from the way it's done on Linux.

Checkout the main branch:
```
git clone -b master https://github.com/darealshinji/qpdfview
cd qpdfview
```

Create localizations:
```
lrelease qpdfview.pro
```

Configure and build:
```
qmake CONFIG+='without_magic without_cups without_signals' qpdfview.pro
make -j4
```

External libraries required are djvulibre, libspectre and poppler.
